name: cloud-login
description: ''
inputs:
  vault_credentials:
    description: ''
    required: false
  aws_credentials:
    description: ''
    required: false
  azure_credentials:
    description: ''
    required: false
  openstack_config:
    description: ''
    required: false
runs:
  using: composite
  steps:
    # Hashicorp Vault #########################################################
    - uses: hashicorp/vault-action@v2
      if: inputs.vault_credentials != ''
      with: ${{ fromJson(inputs.vault_credentials) }}

    # AWS #####################################################################
    - uses: aws-actions/configure-aws-credentials@v4
      if: inputs.aws_credentials != ''
      with: ${{ fromJson(inputs.aws_credentials) }}

    # Azure ###################################################################
    - uses: azure/login@v1
      if: inputs.azure_credentials != ''
      with: ${{ fromJson(inputs.azure_credentials) }}

    # Openstack ###############################################################
    - if: inputs.openstack_config != ''
      run: |
        mkdir -p ${{ github.workspace }}/.config/openstack
        echo "${{ inputs.openstack_config }}" | base64 -d > ${{ github.workspace }}/.config/openstack/cloud.yaml
        echo "OS_CLIENT_CONFIG_FILE=${{ github.workspace }}/.config/openstack/cloud.yaml" | tee -a $GITHUB_ENV
      shell: bash